# https://docusaurus.io/docs/tr/1.1.x/publishing#tips-tricks
# This config file will prevent tests from being run on the gh-pages branch.
version: 2
jobs:
  build:
    machine: true
    branches:
      ignore: master
    steps:
      -run: echo "Skipping tests on master branch."
